# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      python app.py
    displayName: "Run Python Script"

  - script: echo "Build Completed!"
    displayName: "Build Step"

  - script: echo "Deploying Application..."
    displayName: "Deploy Step"
